# Generated by Django 5.2.7 on 2025-11-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, help_text='JWT Token ID (jti claim) - unique identifier for the token', max_length=255, unique=True)),
                ('personal_number', models.CharField(db_index=True, help_text='Patient personal identification number (11 digits)', max_length=11)),
                ('mobile_phone', models.CharField(help_text='Patient mobile phone number (9 digits, without country code)', max_length=9)),
                ('token_type', models.CharField(choices=[('access', 'Access Token'), ('refresh', 'Refresh Token')], help_text='Type of token', max_length=10)),
                ('session_id', models.UUIDField(blank=True, db_index=True, help_text='Session identifier - groups access and refresh tokens together', null=True)),
                ('device_name', models.CharField(blank=True, help_text='Device/browser name (e.g., "Chrome on Windows", "Safari on iPhone")', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was issued')),
                ('expires_at', models.DateTimeField(help_text='When the token expires')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this token was used for authentication', null=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False, help_text='Whether this token has been revoked')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the token was revoked', null=True)),
                ('revocation_reason', models.CharField(blank=True, help_text='Reason for token revocation', max_length=255, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, help_text='IP address from which the token was requested', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from token request', null=True)),
            ],
            options={
                'verbose_name': 'Patient Token',
                'verbose_name_plural': 'Patient Tokens',
                'db_table': 'patient_tokens',
                'indexes': [models.Index(fields=['personal_number', 'is_revoked'], name='patient_tok_persona_1d1c1c_idx'), models.Index(fields=['expires_at', 'is_revoked'], name='patient_tok_expires_322370_idx'), models.Index(fields=['session_id', 'is_revoked'], name='patient_tok_session_8593e0_idx'), models.Index(fields=['personal_number', 'session_id', 'is_revoked'], name='patient_tok_persona_159ac6_idx')],
            },
        ),
    ]
